### ISSUE TITLE
Python3.9 Support

### ISSUE THREAD

**Issue by jdgoodall1** [lumigo-io/python_tracer#248]
I'm trying to trace some python3.9 aws lambdas, without much luck.
I can see that it's not on the supported list yet - any timeline for support? Python 3.9 was released over a year ago at this point

**Comment by efimk-lu** [comment]
Hey @jdgoodall1 we do support python 3.9, I can see that our docs are not updated.

Can add an env variable named `LUMIGO_DEBUG` and set it to `TRUE`

**Comment by jdgoodall1** [comment]
I've managed to work it out - was supplying a bad token.
Thanks for the quick response
